#!/usr/bin/env python3
"""Bake branding guide content into src/branding.py for Lambda deployment.

Reads branding/narrative-styling-guide.md and branding/image-styling-guide.md
and writes their content as Python string constants into src/branding.py.

Run this before sam build, or let deploy.sh call it automatically.

Usage:
    python scripts/bake-branding.py
"""
from pathlib import Path

root = Path(__file__).parent.parent
branding_dir = root / "branding"
out_path = root / "src" / "branding.py"

narrative_path = branding_dir / "narrative-styling-guide.md"
image_path = branding_dir / "image-styling-guide.md"

for p in (narrative_path, image_path):
    if not p.exists():
        print(f"Error: {p} not found")
        raise SystemExit(1)

narrative = narrative_path.read_text(encoding="utf-8")
image = image_path.read_text(encoding="utf-8")

header = '''\
"""Auto-generated by scripts/bake-branding.py — do not edit directly.
To update: edit branding/narrative-styling-guide.md or branding/image-styling-guide.md,
then run `python scripts/bake-branding.py` (deploy.sh does this automatically).
"""
'''

with open(out_path, "w", encoding="utf-8") as f:
    f.write(header)
    f.write("\nNARRATIVE_STYLE = ")
    f.write(repr(narrative))
    f.write("\n\nIMAGE_STYLE = ")
    f.write(repr(image))
    f.write("\n")

print(f"Wrote {out_path}")
print(f"  narrative: {len(narrative)} chars")
print(f"  image:     {len(image)} chars")
